server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql:///postgres
    password: book-password
    username: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: book-service-386415:europe-north1:book-db
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
